# Generated by Django 4.2.7 on 2025-07-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        help_text="Gambar utama produk (akan tetap digunakan untuk kompatibilitas)",
                        upload_to="products/",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link produk (harus berupa URL valid)",
                        max_length=255,
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        default="Link Produk",
                        help_text="Label untuk link produk (misalnya: Link Demo, Link Lainnya)",
                        max_length=50,
                    ),
                ),
                (
                    "additional_link",
                    models.URLField(
                        blank=True,
                        help_text="Link tambahan untuk produk (harus berupa URL valid)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "additional_link_label",
                    models.CharField(
                        blank=True,
                        default="Link Lainnya",
                        help_text="Label untuk link tambahan",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.ImageField(upload_to="services/")),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Link untuk layanan ini", null=True
                    ),
                ),
                ("color", models.CharField(default="blue", max_length=50)),
                (
                    "gradient_color",
                    models.CharField(
                        blank=True,
                        help_text="Warna kedua untuk gradasi",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gradient_type",
                    models.CharField(
                        choices=[
                            ("linear", "Linear Gradient"),
                            ("radial", "Radial Gradient"),
                        ],
                        default="linear",
                        max_length=20,
                    ),
                ),
                (
                    "gradient_direction",
                    models.CharField(
                        choices=[
                            ("to right", "Kanan"),
                            ("to left", "Kiri"),
                            ("to bottom", "Bawah"),
                            ("to top", "Atas"),
                            ("to bottom right", "Kanan Bawah"),
                            ("to bottom left", "Kiri Bawah"),
                            ("to top right", "Kanan Atas"),
                            ("to top left", "Kiri Atas"),
                        ],
                        default="to right",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_photo",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("admin_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "admin_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("admin_description", models.TextField(blank=True, null=True)),
                (
                    "admin_whatsapp",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "footer_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("footer_show_social", models.BooleanField(default=True)),
                ("site_title", models.CharField(blank=True, max_length=100, null=True)),
                ("site_description", models.TextField(blank=True, null=True)),
                (
                    "site_keywords",
                    models.TextField(
                        blank=True, help_text="Comma separated keywords", null=True
                    ),
                ),
                (
                    "site_favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Main favicon image",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "favicon_16",
                    models.ImageField(
                        blank=True,
                        help_text="16x16 favicon",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "favicon_32",
                    models.ImageField(
                        blank=True,
                        help_text="32x32 favicon",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "favicon_apple_touch",
                    models.ImageField(
                        blank=True,
                        help_text="180x180 Apple touch icon",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "favicon_android_192",
                    models.ImageField(
                        blank=True,
                        help_text="192x192 Android chrome icon",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "favicon_android_512",
                    models.ImageField(
                        blank=True,
                        help_text="512x512 Android chrome icon",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "favicon_manifest",
                    models.FileField(
                        blank=True,
                        help_text="Web app manifest file",
                        null=True,
                        upload_to="site/favicon/",
                    ),
                ),
                (
                    "meta_author",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meta_robots",
                    models.CharField(
                        blank=True, default="index, follow", max_length=100, null=True
                    ),
                ),
                (
                    "meta_viewport",
                    models.CharField(
                        blank=True,
                        default="width=device-width, initial-scale=1",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=100, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="site/og/"),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True,
                        default="summary_large_image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "twitter_site",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("github", "GitHub"),
                            ("saweria", "Saweria"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("pinterest", "Pinterest"),
                            ("snapchat", "Snapchat"),
                            ("twitch", "Twitch"),
                            ("reddit", "Reddit"),
                            ("medium", "Medium"),
                            ("behance", "Behance"),
                            ("dribbble", "Dribbble"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("link", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class name", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Keterangan tambahan untuk media sosial",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Social Media",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Judul template untuk referensi", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("greeting", "Salam & Sapaan"),
                            ("business", "Bisnis & Promosi"),
                            ("invitation", "Undangan"),
                            ("thank_you", "Ucapan Terima Kasih"),
                            ("apology", "Permintaan Maaf"),
                            ("reminder", "Pengingat"),
                            ("congratulation", "Ucapan Selamat"),
                            ("holiday", "Hari Raya & Libur"),
                            ("birthday", "Ulang Tahun"),
                            ("motivational", "Motivasi & Inspirasi"),
                            ("announcement", "Pengumuman"),
                            ("follow_up", "Follow Up"),
                            ("other", "Lainnya"),
                        ],
                        default="other",
                        help_text="Kategori template",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(help_text="Isi pesan template")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Deskripsi singkat tentang template",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Jabatan atau deskripsi singkat",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Nomor WhatsApp (format: 628xxxxxxxxxx)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
