# Generated by Django 5.2.4 on 2025-08-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="order",
        ),
    ]
