# Generated by Django 5.2.4 on 2025-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_product_options_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="additional_link",
            field=models.CharField(
                blank=True,
                help_text="Link tambahan untuk produk",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.CharField(
                blank=True, help_text="Link produk", max_length=255, null=True
            ),
        ),
    ]
