# Generated by Django 5.2.4 on 2025-08-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_additional_link_alter_product_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="login_count",
            field=models.IntegerField(default=0, help_text="Jumlah kali login"),
        ),
    ]
